### ISSUE TITLE
Trust all SSL statergy please

### ISSUE THREAD

**Issue by jiachen247** [lightos/Panoptic#17]
Error reason '[SSL: CERTIFICATE_VERIFY_FAILED]

**Comment by lightos** [comment]
I think the best solution would be to add an argument to accept invalid SSL certs, something like --allow-invalid-ssl. I will look into this later this week.

**Comment by jiachen247** [comment]
Yepp thats what i meant. Many programs allow for  an optional --insecure argument where ssl is concern to allow for self signed certs to be used in dev/testing envs.

**Comment by lightos** [comment]
I pushed commit https://github.com/lightos/Panoptic/commit/bc7236c0f346c1a8fea8c27e6892282075c5967c to address this issue. Please test if you can and let me know if it works as expected.
