### ISSUE TITLE
WindowsError occur when url.netloc contains ":" 

### ISSUE THREAD

**Issue by esabear** [lightos/Panoptic#20]
Example URL: https://xxx.com:8080/blah

When creating output directory from parsed_target_url.netloc, ":" is not allowed on Windows.

A quick fix for line 432:
`_ = os.path.join("output", kb.parsed_target_url.netloc)`

to:
`_ = os.path.join("output", kb.parsed_target_url.netloc.replace(":","_"))`

**Comment by esabear** [comment]
And also, if --load from a list that contains ":" like C:\blahblah

That will cause output fail on Windows, too.

A similar fix:
with open(os.path.join(_, "%s.txt" % case.location.replace(args.replace_slash if args.replace_slash else "/", "_")`.replace(":", "_")`), "w") as f:

**Comment by lightos** [comment]
Thanks!
